ask_denisov/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_denisov.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^hello wordl/', include('hello_world.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace="main")),
)

if settings.MEDIA_ROOT:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^question/(?P<quest>\d+)/$', views.question, name='question'),
    url(r'^user/$', views.user, name='user'),
    url(r'^register/$', views.signup, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signin/', views.signin, name='signin'),
    url(r'^signup/', views.signin, name='signup'),
    url(r'^add_question/', views.add, name='add_quest'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^correct/$', views.correct, name='correct'),
    url(r'^correct_email/$', views.correct_Email, name='correct_email'),
    url(r'^correct_pass/$', views.correct_password, name='correct_password'),
    url(r'^correct_Email/$', views.correct_img, name='correct_img'),
    url(r'^$', views.main, name='main'),
)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class MyUser(models.Model):
    user = models.OneToOneField(User)
    rate = models.IntegerField(default=0)
    def __unicode__(self):
        return self.user.username

class Question(models.Model):
    title = models.CharField(max_length=100)
    question_text = models.CharField(max_length=600)
    user = models.ForeignKey(User)
    pubDate = models.DateField('date published')
    rating = models.IntegerField(default=0)
    def __unicode__(self):
        return self.title

class Answer(models.Model):
    ansText = models.CharField(max_length=600)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    pubDate = models.DateTimeField('date published')
    best = models.BooleanField(default='false')
    rating = models.IntegerField(default=0)
    def __unicode__(self):
        return self.ansText

class Tags(models.Model):
    tag = models.CharField(max_length=32, unique=True)
    question = models.ManyToManyField(Question)
    def __unicode__(self):
        return self.tag

class Like(models.Model):
	author = models.ForeignKey(MyUser)
	question = models.ForeignKey(Question)
	status = models.BooleanField(default=False)

main/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.template import RequestContext, loader
from django.core.paginator import Paginator
from main.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from forms import *

from django.core.urlresolvers import reverse

def getQuestion(request):
    if request.GET.get("tag"):
        tag = Tags.objects.filter(tag = request.GET.get("tag")).first()
        if tag is None:
            question = Question.objects.order_by('-pubDate')
        else:
            question = tag.question.order_by('-pubDate')
    else:
        question = Question.objects.order_by('-pubDate')
    return question

def main(request):
    question = getQuestion(request)
    q = Paginator(question,10)
    if request.GET:
        num_page = request.GET.get('page')
        try:
            page = q.page(num_page)
        except PageNotAnInteger:
            page = q.page(1)
            print 'PageNotAnInteger'
            num_page = 1
        except EmptyPage:
            page = q.page(q.num_pages)
            num_page = q.num_pages
            print 'empty'
            print num_page
    else:
        num_page = 1
        page = q.page(num_page)

    last_page = q.num_pages

    for quest in page:
        quest.count = quest.answer_set.count()
        quest.tags = quest.tags_set.all()
        # if request.user.is_authenticated:
        # like = Like.objects.filter(question = quest)
        #     if like.exists():
        #         quest.voice = 0
        #     else:
        # quest.voice = 1
        # else:
        #     quest.voice = 1

    # print members.user.username

    k = []
    for i in range(int(num_page)-4, int(num_page)+4):
        if i in q.page_range:
            k.append(i)

    if last_page <= 1:
        is_paginator = False
    else:
        is_paginator = True
    context = {
        # "profile": prof,
        'actual_page': num_page,
        'last_page': last_page,
        'questions':  page,
        'paginators': k,
        'all_pages': q.num_pages,
        'is_paginator': is_paginator
    }
    default = get_default_context()
    context.update(default)
    return render(request, 'main/content.html', context)

def user(request):
    if request.user.is_authenticated():
        prof = MyUser.objects.get(user_id=request.user.id)
    else:
        prof = ""
    this_user = MyUser.objects.get(user_id=request.GET.get("user"))
    tag = Tags.objects.all()[:10]
    members = MyUser.objects.select_related("user").all().order_by('-rate')[:10]
    context = {
        "profile": prof,
        "this": this_user,
        "mytag": tag,
        "bastMemb": members,
    }
    print prof
    return render(request, 'main/user.html', context)

@login_required(login_url='/signin/')
def ask(request):
    form = Add_question()
    default = get_default_context()
    content = {'form': form}
    content.update(default)
    return render(request, 'main/ask.html', content)

def add(request):
    if request.user.is_authenticated:
        default = get_default_context()
        if request.POST:
            form = Add_question(request.POST, request = request or None)
            if form.is_valid():
                form.save()
                return redirect('/')
            else:
                print 3
                return render(request, 'main/ask.html', default.update({'form':form}))
        else:
            form = Add_question()
            print 4
            return render(request, 'main/ask.html', default.update({'form' : form}))

def question(request, quest):
    # if request.POST:
    #     form = answer_form(request.POST)
    #     if form.is_valid():
    #         form.save()
    #     else:
    #
    form = answer_form()
    if request.GET:
        num_page = request.GET.get('page')
    else:
        num_page = 1
    question = get_object_or_404(Question, id=int(quest))

    answers = question.answer_set.all()
    p = Paginator(answers, 5)
    try:
        page = p.page(num_page)
    except PageNotAnInteger:
        page = p.page(1)
        num_page = 1
    except EmptyPage:
        page = p.page(p.num_pages)
        num_page = p.num_pages
    last_page = p.num_pages

    k=[]

    for i in range(int(num_page)-4, int(num_page)+4):
        if i in p.page_range:
            k.append(i)

    if last_page <= 1:
        is_paginator = False
    else:
        is_paginator = True
    context = {
        "question": question,
        "count": question.answer_set.count(),
        "tags": question.tags_set.all(),
        "answers" : page,
        'is_paginator': is_paginator,
        'last-page': last_page,
        'paginator': k,
        "likes": question.like_set.count(),
        'form':form
    }
    default = get_default_context()
    context.update(default)
    if context["question"]:
        return render(request, 'main/question.html', context)
    else:
        return render(request, 'main/question.html', default)

def register(request):
    context = get_default_context()
    return render(request, 'main/register.html', context)

def signin(request):
    context = get_default_context()
    return render(request, 'main/login.html', context)

def logout(request):
    auth.logout(request)
    return redirect('/')

# def login(request):
#     if request.POST:
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = auth.authenticate(username=username, password=password)
#         if user is not None:
#             auth.login(request, user)
#             return HttpResponse('ok', imetype='text/html')
#         else:
#             return HttpResponse('bad Password!', mimetype='text/html')
#             #return render(request)
#     else:
#         return HttpResponse('error', mimetype="text/html")

def login(request):
    if not request.user.is_authenticated():
        default = get_default_context()
        form = singin_form()
        context = {
            'form':form,
            'bad_user':True
        }
        context.update(default)
        if request.POST:
            form = singin_form(request.POST)
            if form.is_valid():
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = auth.authenticate(username=username, password=password)
                if user is not None:
                    auth.login(request, user)
                    return HttpResponseRedirect('/')
            return render(request,'main/login.html', context)
    else:
        return redirect('/')

@login_required(login_url='/signin/')
def correct_Email(request):
    form = correct_Email_form()
    context = {
        'form': form,
        'btn': 'change'
    }
    default = get_default_context()
    context.update(default)
    if request.POST:
        form = correct_Email_form(request.POST, request.FILES, request = request or None)
        context['form'] = form
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'main/register.html', context)
    return render(request, 'main/register.html', context)

@login_required(login_url='/signin/')
def correct(request):
    default = get_default_context()
    return render(request, 'main/correct.html', default)


@login_required(login_url='/signin/')
def correct_password(request):
    default = get_default_context()
    form = correct_password_form()
    context = {
        'form': form,
        'btn': 'change'
    }
    context.update(default)
    if request.POST:
        form = correct_password_form(request.POST, request.FILES, request = request or None)
        context['form'] = form
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'main/register.html', context)
    return render(request, 'main/register.html', context)

@login_required(login_url='/signin/')
def correct_img(request):
    default = get_default_context()
    form = correct_img_form()
    context = {
        'form': form,
        'btn': 'change'
    }
    context.update(default)
    if request.POST:
        form = correct_img_form(request.POST, request.FILES, request = request or None)
        context['form']=form
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'main/register.html', context)
    return render(request, 'main/register.html', context)

def signup(request):
    form = ProfileUser()
    context = {
        'form': form,
        'btn': 'Register'
    }
    default = get_default_context()
    context.update(default)
    if request.POST:
        form = ProfileUser(request.POST, request.FILES)
        context['form']=form
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'main/register.html', context)
    return render(request, 'main/register.html', context)

def get_default_context():
    tag = Tags.objects.all()[:10]
    members = MyUser.objects.select_related("user").all().order_by('-rate')[:10]
    default_context = {
        "mytag": tag,
        "bastMemb": members,
    }
    return default_context

main/templates/main/ask.html
{% extends "main/base.html" %}
{%block content%}
<!-- ask блок -->
<div class="row backAsk">
    <div class="row questPad">
        <h2>Добавить вопрос</h2>
    </div>
    <div class="row">
        <div id="addQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-10">
                        <div class="row">
                            <form class="form-horizontal" name="ask_form" action="{% url 'main:add_quest' %}" onsubmit="return validate_ask ( );">
                                {%csrf_token%}
                                {% for i in form.visible_fields %}
                                <div class="form-group">
                                    <label class="control-label col-xs-3" for="id_{{i.name}}">{{i.label}}</label>
                                    <div class="col-xs-9">
                                        {{i}}
                                        <!--<input type="text" class="form-control" name="titleAsk" id="title" placeholder="Заголовок вопроса">-->
                                        <div class="{%if not i.error%} none {% endif %}" id="titleName">
                                            <span class="glyphicon glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                            <span class="sr-only">(error)</span>
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                                <br />
                                <div class="form-group">
                                    <div class="col-xs-offset-3 col-xs-9">
                                        <input type="submit" class="btn btn-primary" value="Задать вопрос">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock content%}

main/templates/main/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
    <link href="{%static 'main/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/css/myCSS.css'%}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!--<script src="{%static 'main/js/bootstrap.js'%}"></script>-->
    <script src="{%static 'main/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'main/js/myCode.js' %}"></script>
</head>
<body class="backBody">

    <div class = "row">
        <div class="row">
        {% include "main/head.html"%}
        </div>

        <div class="row">
            <div class="col-xs-8 marCont">
                {% block content %}
                {% endblock content%}
            </div>
            <div class="col-xs-2">
                    {% include "main/tags.html"%}
            </div>
        </div>
    </div>
</body>
</html>

main/templates/main/content.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block content %}
{% for q in questions %}
<div class="row ask backAsk">
    <div class="col-xs-3">
        <!-- аватарка по идее грузится из аплоадса -->
        <div class="row myAvPage">
            <p>{{ q.user.username }}</p>
        </div>
        <div class="row myAvPage">
            <img  src="{{ q.user.myuser.img.url }}" class="img-thumbnail img-responsive myAvIm">
        </div>
        <!-- под аватаркой кнопочки и рейтинг -->
        <div class="row">
            <div class="col-xs-4 ">
                <button type="button" class="btn btn-danger lLaik">-</button>
            </div>
            <div class="col-xs-4">
                <div class="reit">
                    <p align="center">{{q.rating}}</p>
                </div>
            </div>
            <div class="col-xs-4">
                <button type="button" class="btn btn-success rLaik">+</button>
            </div>
        </div>
    </div>
    <!-- сам вопрос и пространство под ним -->
    <div class="col-xs-9">
        <!-- url 'main:question' -->
        <div class="row"><a href="/question/{{ q.id }}/"><h2 class="clearM">{{q.title}}</h2></a></div>
        <div class="row">
            <p style="word-wrap: break-word;" class="ques">{{ q.question_text }}</p>
        </div>
        <div class="row">
            <div class="col-xs-3"><a href="/question/{{ q.id }}/">Answer({{q.count}})</a></div>

            <div class="col-xs-5">
                <p>
                    Tags:
                {% for tag in q.tags%}
                    <a href="/?tag={{tag.tag}}">{{tag.tag}}</a>,
                {%endfor%}
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}


{% if is_paginator %}
<div class="pagMarg">
    <nav>
        <ul class="pagination">
            <li>
                <a href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for i in paginators %}
            <li ><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}
            <li>
                <a href="?page={{last_page}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endif %}
{% endblock content %}

main/templates/main/correct.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block content %}
<div style="text-align:center;">
    <div class="row">
        <a href="{% url 'main:correct_email' %}"><div class="btn btn-primary col-md-5" style="margin-top:5%; margin-left:25%;"><p style="font-size:20px; margin:auto">Редактировать Email</p></div></a>
    </div>
    <div class="row">
        <a href="{% url 'main:correct_password' %}"><div class="btn btn-primary col-md-5" style="margin-top:5%; margin-left:25%;"><p style="font-size:20px; margin:auto">Редактировать пароль</p></div></a>
    </div>
    <div class="row">
        <a href="{% url 'main:correct_img' %}"><div class="btn btn-primary col-md-5" style="margin-top:5%; margin-left:25%;"><p style="font-size:20px; margin:auto">Редактировать картинку</p></div></a>
    </div>
</div>

{% endblock %}

main/templates/main/head.html
{%load staticfiles%}
<div class="row topCol">
    <div class="col-xs-3 logo">
        <a href="{%url 'main:main'%}"><h1 class="wCol">Ask-Denisov</h1></a>
    </div>

    <!-- задать вопрос -->

    <div class="col-xs-2 sear">
        <!--location.href=/{%url 'main:ask'%}-->
        <button type="button"  class="btn btn-success askBtn" onclick="location.pathname='{%url 'main:ask'%}'">Задать вопрос</button>
    </div>

    <!-- строка поиска -->

    <div class="col-xs-3 sear">
        <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Найти</button>
        </form>
    </div>
    {%if user.is_authenticated %}
    <!-- отдел вошедшего пользователя -->
    <div class="col-xs-4">
        <div class="row">
            <!-- аватарка пользоваеля -->
            <div class="col-xs-3 myAvTop">
                <img src="{{user.myuser.img.url}}" class="img-thumbnail img-responsive myAvTop">
            </div>
            <!-- инфо пользоввателя имя, настройки, выйти -->
            <div class="col-xs-8">
                <div class="row">
                    <a href="/user/?user={{user.id}}"><h2 class="userTName">{{user}}</h2></a>
                </div>
                <div class="row">
                    <div class="col-xs-3 clearP">
                        <a href="{% url 'main:correct' %}"><p class="TopLogBtn">Settings</p></a>
                    </div>
                    <div class="col-xs-3 clearP">
                        <a href="{% url 'main:logout' %}"><p class="TopLogBtn">log out</p></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <!-- отдел не вошедшего пользователя -->
    <div class="col-xs-4" >
        <div class="row">
            <!-- логинься или регайся -->
            <!--<div class="col-xs-3 reit topMarg5"><a href=""><p class="TopLogBtn">Log in</p></a></div>-->
            <!-- Button trigger modal -->
            <div class="col-xs-3 reit topMarg5">
                <button type="button" class="btn btn-primary btn-lg" onclick="location.href='{% url 'main:signin' %}'">
                    Log in
                </button>
            </div>
            <div class="col-xs-3 reit topMarg5">
                <button type="button" class="btn btn-primary btn-lg" onclick="location.href='{% url 'main:register' %}'">
                    Registr
                </button>
            </div>
            <!--<div class="col-xs-3 reit topMarg5"><a href="http://localhost/main/register"><p class="TopLogBtn">Register</p></a></div>-->
        </div>
    </div>
    {% endif %}
</div>

main/templates/main/login.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block content %}
<!-- Modal -->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Log in</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                {% if bad_user %}
                <div class="row badUser"> <p> некорректный кользователь </p> </div>
                {% endif %}
                <div class="col-xs-10">
                    <div class="row">
                        <form class="form-horizontal" method="post" name="login_form" action="/login/" onsubmit="return validate_login_form ( );">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-xs-3" for="loginName">login</label>
                                <div class="col-xs-9">
                                    <input type="text" class="form-control" name="username" id="loginName" placeholder="Введите логин">
                                    <div class="none" id="logName">
                                        <span class="glyphicon glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                        <span class="sr-only">(error)</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-xs-3" for="controlPassword">Пароль:</label>
                                <div class="col-xs-9">
                                    <input type="password" class="form-control" id="controlPassword" name="password" placeholder="Введите пароль">
                                    <div class="none" id="logPass">
                                        <span class="glyphicon glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                        <span class="sr-only">(error)</span>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-xs-offset-3 col-xs-9">
                                    <input type="submit" class="btn btn-primary" value="Log in">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
            <!-- конец модального окна логина-->
{%endblock%}

main/templates/main/question.html
{% extends "main/base.html" %}
{%load staticfiles%}
{%block content%}
<div class="row ask backAsk">
    <div class="col-xs-3">
        <!-- аватарка по идее грузится из аплоадса -->
        <p style="text-align:center">{{question.user.username}}</p>
        <div class="row myAvPage">
            <img src="{{question.user.myuser.img.url}}" class="img-thumbnail img-responsive">
        </div>
        <!-- под аватаркой кнопочки и рейтинг -->
        <div class="row">
            <div class="col-xs-4">
                <button type="button" class="btn btn-danger lLaik">-</button>
            </div>
            <div class="col-xs-4">
                <div class="reit">
                    <p align="center">{{question.rating}}</p>
                </div>
            </div>
            <div class="col-xs-4 ">
                <button type="button" class="btn btn-success rLaik">+</button>
            </div>
        </div>
    </div>
    <!-- сам вопрос и пространство под ним -->
    <div class="col-xs-9">
        <div class="row"><h2 class="clearM">{{question.title}}</h2></div>
        <div class="row">
            <p class="ques">{{question.question_text}}</p>
        </div>
    </div>
</div>

<div class="row backAsk">
    <div class="row questPad">
        <h4>добавить ответ</h4>
    </div>
    <div class="row">
        <div id="addQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-10">
                        <div class="row">
                            <form class="form-horizontal" method="post" name="ask_form" action="{% url 'main:add_quest' %}" onsubmit="return validate_ask ( );">
                                {%csrf_token%}
                                {% for i in form.visible_fields %}
                                <div class="form-group">
                                    <label class="control-label col-xs-3" for="id_{{i.name}}">{{i.label}}</label>
                                    <div class="col-xs-9">
                                        {{i}}
                                        <!--<input type="text" class="form-control" name="titleAsk" id="title" placeholder="Заголовок вопроса">-->
                                        <div class="{%if not i.errors%} none {% endif %}" id="titleName">
                                            <span class="glyphicon glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                            <span class="sr-only">(error)</span>
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                                <br />
                                <div class="form-group">
                                    <div class="col-xs-offset-3 col-xs-9">
                                        <input type="submit" class="btn btn-primary" value="добавить ответ">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="row backAsk topMarg5">
        <!-- ответы -->
        {%for answer in answers%}
        <div class="row  answer">
            <div class="col-xs-12">
                <div class="col-xs-3">
                    <!-- аватарка по идее грузится из аплоадса -->
                    <p style="text-align:center">{{answer.user.username}}</p>
                    <div class="row myAvPage">
                        <img src="{{answer.user.myuser.img.url}}" class="img-thumbnail img-responsive">
                    </div>
                    <!-- под аватаркой кнопочки и рейтинг -->
                    <div class="row">
                        <div class="col-xs-4">
                            <button type="button" class="btn btn-danger lLaik">-</button>
                        </div>
                        <div class="col-xs-4">
                            <div class="reit">
                                <p align="center">1000</p>
                            </div>
                        </div>
                        <div class="col-xs-4 ">
                            <button type="button" class="btn btn-success rLaik">+</button>
                        </div>
                    </div>
                </div>
                <!-- сам вопрос и пространство под ним -->
                <div class="col-xs-9">
                        <div class="row ansText">
                            <p class="ques">
                                {{answer.ansText}}
                            </p>
                        </div>

                </div>
                <div class="row bestAns">
                    <a><p>лучший ответ</p></a>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

<!-- пагинатор -->
{% if is_paginator %}
<div class="pagMarg">
    <nav>
        <ul class="pagination">
            <li>
                <a href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for i in paginators %}
                <li ><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}
            <li>
                <a href="?page={{last_page}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endif %}
{%endblock content%}

main/templates/main/tags.html
<div class = "row">

    <ul class="list-unstyled myTags">
        <li> Тэги: </li>
        {%for tag in mytag %}
            <li><a href="/?tag={{tag}}">{{tag}}</a></li>
        {%endfor%}
        <li> Лучшие пользователи:</li>
        {%for members in bastMemb %}
            <li><a href="/user/?user={{members.user.id}}">{{members.user.username}}</a></li>
        {%endfor%}
    </ul>
</div>

main/templates/main/user.html
{% extends "main/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="row ask backAsk">
    <div class="col-xs-3">
        <!-- аватарка по идее грузится из аплоадса -->
        <div class="row myAvPage">
            <img  src="{{this.user.myuser.img.url}}" class="img-thumbnail img-responsive myAvIm">
        </div>
        <!-- под аватаркой кнопочки и рейтинг -->
    </div>
    <!-- сам вопрос и пространство под ним -->
    <div class="col-xs-9">
        <!-- url 'main:question' -->
        <div class="row"><h2 class="clearM">Ваш профиль</h2></div>
        <div class="row">
            <p class="ques">{{ this.user.username }}</p>
            <p class="ques">{{ this.user.email }}</p>
        </div>
    </div>
</div>
{% endblock content %}